version: "3.8"
services:
    mongodb:
        build:
            context: .
        restart: always
        ports:
            - 27017:27017
    nest:
        build:
            context: ./application
        ports:
            - 4488:4488
            - 4489:4488
    react:
        build:
            context: ./application/frontend
        ports:
            - 4487:4487
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - 80:80
            - 443:443