version: "3.8"
services:
    mongodb:
        build:
            context: .
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    nest:
        build:
            context: ./application
        ports:
            - 4488:4488
            - 4489:4488
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - 80:80
            - 443:443