name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: dac27ac0-03b9-477e-b8ab-51c9e63abada
          heroku_app_name: "wl-chatbot"
          heroku_email: "shulgamalthael@gmail.com"
          usedocker: true